apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "dev-cluster"
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://mboersma.github.io/cluster-api-charts'
    chart: azure-aks-aso
    targetRevision: v0.4.3
    helm:
      valuesObject:
        clusterName: "dev-cluster"
        location: "eastus"
        subscriptionID: "c55ff92b-0429-4593-b3b1-9a1932d398c5"
        clientID: "685bd068-9e3b-4cfa-a451-1c85330c4ef0"
        tenantID: "c8eca3ca-1276-46d5-9d9d-a0f2a028920f"
        authMode: "workloadidentity"
        kubernetesVersion: v1.35.0
        clusterNetwork: "overlay"
        withClusterClass: true
        withClusterTopology: true
        managedMachinePoolSpecs:
          pool0:
            count: 1
            enableAutoScaling: true
            enableEncryptionAtHost: false
            enableFIPS: false
            enableNodePublicIP: false
            enableUltraSSD: false
            maxCount: 3
            minCount: 1
            mode: System
            osSKU: AzureLinux
            vmSize: Standard_DS2_v2
            type: VirtualMachineScaleSets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
